### ISSUE TITLE
I can't see visualized result when running the demo called conv3d_sep2

### ISSUE THREAD

**Issue by ghost** [VisualComputingInstitute/TrackR-CNN#50] opened 2019-12-12 16:03 UTC
I first extract the three files conv3d_sep2-00000005* to models/conv3d_sep2/
And ran this command in my terminal:

`
python3 main.py configs/conv3d_sep2 "{\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,\"video_tags_to_load\":[\"0002\",\"0006\",\"0007\",\"0008\",\"0010\",\"0013\",\"0014\",\"0016\",\"0018\",\"0000\",\"0001\",\"0003\",\"0004\",\"0005\",\"0009\",\"0011\",\"0012\",\"0015\",\"0017\",\"0019\",\"0020\"]}"
`

Then ran this:

`
python3 main.py configs/conv3d_sep2 "{\"build_networks\":false,\"import_detections\":true,\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"do_tracking\":true,\"visualize_detections\":true,\"visualize_tracks\":false,\"load_epoch_no\":5,\"video_tags_to_load\":[\"0002\",\"0006\",\"0007\",\"0008\",\"0010\",\"0013\",\"0014\",\"0016\",\"0018\"]}"
`

but failed to visualize the tracking results.
Or I might have misunderstood your meanings in README.md.

here are some warnings from tensorflow

`W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.`
and this
`2019-12-12 23:23:20.885099: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
`

hope you could help.

**Comment by pvoigtlaender** [comment] 2019-12-13 14:39
Maybe the problem is
failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
?

Please make sure you have a GPU and that CUDA and TensorFlow with cuda support is properly installed.

**Comment by ghost** [comment] 2019-12-14 13:27
thank for your reply
I'll have a try.

**Comment by ahnonay** [comment] 2020-01-06 19:21
Closing this for now, please reopen if needed

**Closed as completed by ahnonay** 2020-01-06 19:21 UTC
