### ISSUE TITLE
Input size of the MOTchallenge dataset

### ISSUE THREAD

**Issue by ifzhang** [VisualComputingInstitute/TrackR-CNN#8] opened 2019-07-03 03:04 UTC
Thanks for sharing! I'm trying to train on the MOTSchallenge dataset. The four sequences in the MOTSchallenge dataset have different image sizes, so what is the "input_size_train" in the config of MOTSchallenge dataset? When I validate the MOTSchallenge dataset, is the "input_size_val" of the four sequences different? @pvoigtlaender

**Comment by pvoigtlaender** [comment] 2019-07-03 08:58
Hi,

for MOTSChallenge we used the following settings in the config:

  "resize_mode_train": "resize_min_short_edge_max_long_edge",
  "input_size_train": [420, 1024],
  "resize_mode_val": "resize_min_short_edge_max_long_edge",
  "input_size_val": [540, 1024],

**Comment by pvoigtlaender** [comment] 2019-07-10 10:20
I assume that the issue is solved and will close it. Feel free to reopen if you have further doubts.

**Closed as completed by pvoigtlaender** 2019-07-10 10:20 UTC
