### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by josh-goldman1** [VisualComputingInstitute/TrackR-CNN#33] opened 2019-09-28 18:36 UTC
When I run python main.py configs/conv3d_sep2
I get the following error:

Traceback (most recent call last):
  File "main.py", line 39, in <module>
    tf.app.run(main)
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/venv/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 34, in main
    engine = Engine(config)
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/core/Engine.py", line 41, in __init__
    name="trainnet")
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/network/Network.py", line 16, in __init__
    self.input_tensors_dict = dataset.create_input_tensors_dict(self.batch_size)
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/datasets/Dataset.py", line 270, in create_input_tensors_dict
    self._load_inputfile_lists()
  File "/Users/joshgoldman/PycharmProjects/TrackR-CNN/datasets/Dataset.py", line 254, in _load_inputfile_lists
    assert len(l) > 0
AssertionError

**Comment by josh-goldman1** [comment] 2019-09-28 18:37
My config file:
"KITTI_segtrack_data_dir": "/Users/joshgoldman/PycharmProjects/TrackR-CNN/assets/KITTI/kitti_mots/images/testing/image_02/0000/",
"load_init": "/Users/joshgoldman/PycharmProjects/TrackR-CNN/models/conv3d_sep2"

**Comment by josh-goldman1** [comment] 2019-09-28 18:40
my mistake. My config file:
"KITTI_segtrack_data_dir": "/Users/joshgoldman/PycharmProjects/TrackR-CNN/assets/KITTI/kitti_mots/images"
"load_init": "/Users/joshgoldman/PycharmProjects/TrackR-CNN/models/conv3d_sep2"

**Comment by EchoAmor** [comment] 2019-09-29 02:08
I meet the error too, but when I use the other 2 commands  ,it works well

> python main.py configs/conv3d_sep2 "{\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,\"video_tags_to_load\":[\"0002\",\"0006\",\"0007\",\"0008\",\"0010\",\"0013\",\"0014\",\"0016\",\"0018\",\"0000\",\"0001\",\"0003\",\"0004\",\"0005\",\"0009\",\"0011\",\"0012\",\"0015\",\"0017\",\"0019\",\"0020\"]}"

This one works well,how can solve this problem ? @pvoigtlaender

**Comment by ahnonay** [comment] 2019-10-03 16:41
Closing this because as far as I can understand, the issue of @josh-goldman1 is resolved. Please reopen if needed.
@EchoAmor I can't really tell from your comment what the problem is. Which commands are working, which ones aren't? If you still have problems, please create a !new! issue describing exactly which error you get.

**Closed as completed** 2019-10-03 16:42 UTC
